<?php
$this->placeholder('page_title')->set(sprintf('%s(%s)', $this->user->username, $this->user->name()))
?>

<dl>
<dt>Username</td>
<dd><?= $this->user->username ?>&nbsp;</dd>

<dt>Name</dt>
<dd><?= $this->user->name() ?>&nbsp;</dd>

<dt>eMail</dt>
<dd><?= $this->user->email ?>&nbsp;</dd>

</dl>
	<?= new Zupal_Control_IconLink(ZUPAL_BASEURL . 'edit.gif', 'Edit', array(
	'module' => 'people',
	'controller' => 'users',
	'action' => 'edit',
	'id' => $this->user->identity()
	)) ?>
	<?= new Zupal_Control_IconLink(ZUPAL_BASEURL . 'x.gif', 'Delete', array(
	'module' => 'people',
	'controller' => 'users',
	'action' => 'delete',
	'id' => $this->user->identity()
	)) ?>