<?
	$this->placeholder('page_title')->set('Media Home Page');
?>

<table width="80%" align="center">
	<tr>
		<th width="1*">Artists</th>


	</tr>

	<tr>
		<td>
			<ul>
		<? foreach(Zupal_Media_Artists::getInstance()->findAll('performs_as') as $artist): ?>
				<li><?= $artist->name() ?></li>
		<? endforeach; ?>
			</ul>

			<?= $this->link('New Artist', array(
				'module' => 'media',
				'controller' => 'artists',
				'action' => 'new'
			)) ?>
		</td>
	</tr>

</table>