<?php

	$this->placeholder('page_title')->set('View Resource &quot;' . $this->res->label . '&quot;');

?>

<dl>

<dt>ID</dt>
<dd><?= $this->res->id ?></dd>

<dt>Label</dt>
<dd><?= $this->res->label ?></dd>

<dt>Note</dt>
<dd><?= $this->res->notes ?></dd>

</dl>
<?= new Zupal_Control_IconLink('edit.gif', 'Edit Role', array('module' => 'admin',
		'controller' => 'acl',
		'action' => 'editres',
		'id' => $this->res->id
	)) ?>
<?= new Zupal_Control_IconLink('x.gif', 'Delete Role', array('module' => 'admin',
		'controller' => 'acl',
		'action' => 'deleteres',
		'id' => $this->res->id
	)) ?>