<?php

/**
 * Node
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5441 2009-01-30 22:58:43Z jwage $
 */
class Node extends BaseNode implements Zupal_Node_INode,
	Zupal_IDomain
{

	public function nodeId(){ return $this->id; }

	public function find(array $searchCrit, $sort = NULL)
	{
		$q = Doctrine_Query::create();

		foreach($searchCrit as $key => $value){
			if (is_numeric($value)) {
				$q->where("`$key` = ?", $value);
			} else {
				$q->where("`$key` LIKE ?", $value);
			}
		}

		return $q->execute(array(), Doctrine::HYDRATE_RECORD);
	}

	public function findOne(array $searchCrit, $sort = NULL)
	{
		$q = Doctrine_Query::create();

		foreach($searchCrit as $key => $value){
			if (is_numeric($value)) {
				$q->where("`$key` = ?", $value);
			} else {
				$q->where("`$key` LIKE ?", $value);
			}
		}
		$q->limit(1);

		return array_pop($q->execute(array(), Doctrine::HYDRATE_RECORD));
	}
}