<?
	$this->placeholder('page_title')->set($this->content->title());
?>
<p>
	<?= $this->content->text() ?>
</p>
<fieldset  class="ilist">
	<legend><?= $this->content->shortTitle() ?></legend>
<ul>
	<li>
		<?= new Zupal_Control_IconLink('edit.gif', 'Edit', array('module' => 'content',
		'controller' => 'admin',
		'action' => 'edit',
		'id' => $this->content->identity(),
		'placement' => Zupal_Control_Icon::PLACEMENT_HORIZONTAL
	)) ?> 
	</li>

	<li>
		<?=  new Zupal_Control_IconLink('x.gif', 'Delete', array('module' => 'content',
		'controller' => 'admin',
		'action' => 'delete',
		'id' => $this->content->identity(),
		'placement' => Zupal_Control_Icon::PLACEMENT_HORIZONTAL
	)) ?>
	</li>

</ul>

</fieldset>