<?
$this->placeholder('page_title')->set('Ultimanager');

$params = array('panel' => 'ult_admin');
$mm = Model_Menu::getInstance();
if (!$menus = $mm->find($params, 'sort_by')):
    $module = Administer_Model_Modules::getInstance()->get('ultimatum');
    $menu = $module->config_node('admin_menu');

    $mm->add_menus($menu, 'ultimatum');
endif;

$pages = $mm->pages('ult_admin');

echo '<span class="button_link_list">', $this->navigation()->menu($pages), '</span>';