<?php echo $this->doctype() ?>
<html>
<head>
    <link href="<?= $this->baseUrl() ?><?= preg_replace('~^' . ZUPAL_PUBLIC_PATH . '~', '', dirname(__FILE__)) ?>/admin.css"
          media="all" rel="stylesheet" type="text/css" />
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="/" />
</head>

<body>
    <?= $this->zupalusermenu() ?>
    <div id="menu">
        <?= $this->zupalmenus() ?>
    </div>
    <h1><?= $this->placeholder('page_title' )?></h1>
    <?php echo $this->layout()->content ?>
</body>

</html>