<?php echo $this->doctype() ?>
<?
error_log(print_r(get_include_path(), 1));
?>
<html>
<head>
<?
    $this->zupallayoutcss('style.css', __FILE__);
    if ($this->dojo()->isEnabled()){
    $this->dojo()->setLocalPath('/scripts/dojo/dojo.js')// changing to root scripts
                 ->addStyleSheetModule('dijit.themes.tundra');
    echo $this->dojo();
}
?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="/" />
</head>

<body class="tundra">
    <div id="menu">
        <?= $this->zupalmenus() ?>
    </div>
    <div id="main">
    <?= $this->zupalusermenu() ?>
    <?= $this->zupalalerts() ?>

    <h1><?= $this->placeholder('page_title' )?></h1>
    <?php echo $this->layout()->content ?>
    </div>
</body>

</html>