<?php echo $this->doctype() ?>
<html>
<head>
<?
    $this->zupallayoutcss('style.css', __FILE__);
    $this->zupallayoutcss('admin.css', __FILE__);
?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript() ?>
    <base href="/" />
</head>

<body>
    <div id="menu">
        <?= $this->zupalmenus() ?>
    </div>
    <?= $this->zupalusermenu() ?>
    <div id="main">
    <h1><?= $this->placeholder('page_title' )?></h1>
    <?php echo $this->layout()->content ?>
    </div>
</body>

</html>