<?php
$this->placeholder('page_title')->set(sprintf('%s(%s)', $this->user->username, $this->user->name()))
?>

<?= $this->form ?>

<?= new Zupal_Control_IconLink(ZUPAL_BASEURL . 'view.gif', 'View', array(
'module' => 'people',
'controller' => 'users',
'action' => 'view',
'id' => $this->user->identity()
)) ?>
<?= new Zupal_Control_IconLink(ZUPAL_BASEURL . 'x.gif', 'Delete', array(
'module' => 'people',
'controller' => 'users',
'action' => 'delete',
'id' => $this->user->identity()
)) ?>