<?

$this->placeholder('page_title')->set('Artist Search Result');
$header = FALSE;
$first = FALSE;
?>
<form method="post" action="<?= ZUPAL_BASEURL ?>/media/artists/mbartist">
<table>


<? foreach($this->artists as $k => $l): ?>
<? if (!$header): ?>
<tr>
	<th>&nbsp;</th>
	<th>
	<?= join('</th><th>', array_keys((array) $l)) ?>
</th>
</tr>
<? 
$header = TRUE;
endif; 
?>
<tr>
	<td>
		<input type="radio" name="mb_id"
		<? if(!$first) echo ' checked="checked" ' ?> value="<?= $l->mbid ?>">
	</td>

	<td><?= join('</td><td>', (array) $l) ?></td>
</tr>
<? 
$first = TRUE;
endforeach; 
 ?>
</table>
<input type=submit value="Add Artist From MusicBrainz" />