<?

$this->placeholder('page_title')->set('Artist Search Result');

$list = Zupal_Media_MusicBrains::digest_result($this->result);
$list = $list['artist-list'];
?>
<form method="post" action="<?= ZUPAL_BASEURL ?>/media/artists/mbartist">
<table>
<tr>
	<th>&nbsp;</th>
	<th>
	<?= join('</th><th>', array_keys($list[0])) ?>
</th></tr>

<? foreach($list as $k => $l): ?>
<tr>
	<td>
		<input type="radio" name="musicbrainz_id" <? if(!$k) echo ' checked="checked" ' ?> value="<?= $l['id'] ?>">
	</td>

	<td><?= join('</td><td>', $l) ?></td>
</tr>
<? endforeach; ?>
</table>
<input type=submit value="Add Artist From MusicBrainz" />