<?

$this->placeholder('page_name')->set($this->artist->name());
?>
<dl>

	<dt>True Name</dt>
	<dd><?= $this->artist->person()->name() ?>&nbsp;</dd>

	<dt>performs as</dt>
	<dd><?= $this->artist->name() ?>&nbsp;</dd>

	<dt>Type</dt>
	<dd><?= $this->artist->type ?></dd>

	<dt>Gender</dt>
	<dd><?= $this->artist->person_gender ?>&nbsp;</dd>
</dl>

<fieldset>
	<legend>Relationships</legend>

	<table width="100%">
		<thead>
		<tr>
			<th>Name</th>
			<th colspan="2">Duration</th>
			<th colspan="2">Type</th>
			<th>Meta</th>
		</tr>
		</thead>
		<tbody>
		<? foreach($this->data->get_relations() as $row): ?>
			<tr>
				<td>
					<?= $row->get_name() ?>
				</td>
				<td> <?= $row->get_begin() ?></td>

				<td> <?= $row->get_end() ?></td>
				<td>
					<?= $row->get_type() ?>
				</td>

				<td>
					<?= $row->get_relationship() ?>
				</td>


				<td><pre><?= $row->meta() ?></pre></td>
			</tr>
		<? endforeach; ?>
		</tbody>

	</table>


</fieldset>


<fieldset class="ilist">
	<legend><?= $this->artist->name() ?></legend>
<ul>
	<li>
		<?= new Zupal_Control_IconLink('edit.gif', 'Edit', array('module' => 'media',
		'controller' => 'artists',
		'action' => 'edit',
		'node_id' => $this->artist->nodeId(),
		'placement' => Zupal_Control_Icon::PLACEMENT_HORIZONTAL
	)) ?>
	</li>

	<li>
		<?=  new Zupal_Control_IconLink('x.gif', 'Delete', array('module' => 'media',
		'controller' => 'artists',
		'action' => 'delete',
		'id' => $this->artist->identity(),
		'placement' => Zupal_Control_Icon::PLACEMENT_HORIZONTAL
	)) ?>
	</li>
</ul>
</fieldset>
<pre><? print_r($this->data) ?></pre>