<?

$this->placeholder('page_name')->set($this->artist->name());
?>
<table>
	<tr><td valign="top">
<dl>

	<dt>True Name</dt>
	<dd><?= $this->artist->person()->name() ?>&nbsp;</dd>

	<dt>performs as</dt>
	<dd><?= $this->artist->name() ?>&nbsp;</dd>

</dl>
<fieldset  class="ilist">
	<legend><?= $this->artist->name() ?></legend>
<ul>
	<li>
		<?= new Zupal_Control_IconLink('edit.gif', 'Edit', array('module' => 'media',
		'controller' => 'artist',
		'action' => 'edit',
		'id' => $this->artist->identity(),
		'placement' => Zupal_Control_Icon::PLACEMENT_HORIZONTAL
	)) ?>
	</li>

	<li>
		<?=  new Zupal_Control_IconLink('x.gif', 'Delete', array('module' => 'media',
		'controller' => 'artist',
		'action' => 'delete',
		'id' => $this->artist->identity(),
		'placement' => Zupal_Control_Icon::PLACEMENT_HORIZONTAL
	)) ?>
	</li>
</ul>
</td>
<td valign="top">
	<pre>
<? print_r($this->relat) ?>
	</pre>
</td></tr>
</table>
</fieldset>