<?
$this->placeholder('page_title')->set('Play Ultimatum!');

if ($this->nouser):
    echo $this->filepage('ultima_game_nouser', "/game/nouser.html", NULL, 'ultimatum');
else:
    echo $this->filepage('ultima_game_intro', "/game/intro.html", NULL, 'ultimatum');
endif;
if (!$this->nouser):
?>
<ul>
<? foreach($this->games as $game): ?>
    <li><a href="<?= $this->baseUrl() ?>/ultimatum/game/run/<?= $game->identity() ?>">
<?= $game->get_title() ?></a>
<? endforeach; ?>
</ul>
<? if (count($this->games)): ?>
<h2>... or start a new game </h2>
<? else: ?>
<h2>Start a new game</h2>
<? endif; ?>
<?= new Ultimatum_Form_Ultgames() ?>
<? endif; ?>