<?
$this->placeholder("page_title")->set("Table Definiitions");
?>
<table>
<tr>
<th>Tables</th>
<th>Code </th>
</tr>

<tr>
	<td valign="top">
<dl>
<? foreach($this->tables as $table): ?>
	<dt>
		<?=  new Zupal_Control_Link($table, array('target' => 'table_def',
				'module' => 'admin',
				'controller' => 'modules',
				'action' => 'tableclass',
				'table' => $table)) ?>
	</dt>
<? endforeach; ?>
</dl>
</td>
<td valign=top>
	<iframe name="table_def" width="600" height="800">
	<p>Click a link at the left</p>
	</iframe>
</td>