<?
$this->placeholder('page_title')->set('Synerg Manager');

$params = array('panel' => 'synerg_admin');
$mm = Model_Menu::getInstance();
if (!$menus = $mm->find($params, 'sort_by')):
    $module = Administer_Model_Modules::getInstance()->get('synerg');
    $menu = $module->config_node('admin_menu');

    $mm->add_menus($menu, 'synerg');
endif;

$pages = $mm->pages('synerg_admin');

echo '<span class="button_link_list">', $this->navigation()->menu($pages), '</span>';