
CREATE TABLE IF NOT EXISTS `zupal_place_countries` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `name` varchar(255) NOT NULL,
  `code` varchar(3) NOT NULL,
  `has_states` tinyint(4) NOT NULL default '1',
  `lat` float NOT NULL,
  `long` float NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `code` (`code`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=247 ;

REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (1, 'Andorra', 'AD', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (2, 'United Arab Emirates', 'AE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (3, 'Afghanistan', 'AF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (4, 'Antigua and Barbuda', 'AG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (5, 'Anguilla', 'AI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (6, 'Albania', 'AL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (7, 'Armenia', 'AM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (8, 'Netherlands Antilles', 'AN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (9, 'Angola', 'AO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (10, 'Antarctica', 'AQ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (11, 'Argentina', 'AR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (12, 'American Samoa', 'AS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (13, 'Austria', 'AT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (14, 'Australia', 'AU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (15, 'Aruba', 'AW', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (16, 'Aland Islands Åland Islands', 'AX', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (17, 'Azerbaijan', 'AZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (18, 'Bosnia and Herzegovina', 'BA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (19, 'Barbados', 'BB', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (20, 'Bangladesh', 'BD', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (21, 'Belgium', 'BE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (22, 'Burkina Faso', 'BF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (23, 'Bulgaria', 'BG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (24, 'Bahrain', 'BH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (25, 'Burundi', 'BI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (26, 'Benin', 'BJ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (27, 'Saint Barthélemy', 'BL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (28, 'Bermuda', 'BM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (29, 'Brunei Darussalam', 'BN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (30, 'Bolivia', 'BO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (31, 'Brazil', 'BR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (32, 'Bahamas', 'BS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (33, 'Bhutan', 'BT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (34, 'Bouvet Island', 'BV', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (35, 'Botswana', 'BW', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (36, 'Belarus', 'BY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (37, 'Belize', 'BZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (38, 'Canada', 'CA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (39, 'Cocos (Keeling) Islands', 'CC', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (40, 'Congo, the Democratic Republic of the', 'CD', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (41, 'Central African Republic', 'CF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (42, 'Congo', 'CG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (43, 'Switzerland', 'CH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (44, 'Cote d''Ivoire Côte d''Ivoire', 'CI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (45, 'Cook Islands', 'CK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (46, 'Chile', 'CL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (47, 'Cameroon', 'CM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (48, 'China', 'CN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (49, 'Colombia', 'CO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (50, 'Costa Rica', 'CR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (51, 'Cuba', 'CU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (52, 'Cape Verde', 'CV', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (53, 'Christmas Island', 'CX', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (54, 'Cyprus', 'CY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (55, 'Czech Republic', 'CZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (56, 'Germany', 'DE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (57, 'Djibouti', 'DJ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (58, 'Denmark', 'DK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (59, 'Dominica', 'DM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (60, 'Dominican Republic', 'DO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (61, 'Algeria', 'DZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (62, 'Ecuador', 'EC', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (63, 'Estonia', 'EE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (64, 'Egypt', 'EG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (65, 'Western Sahara', 'EH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (66, 'Eritrea', 'ER', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (67, 'Spain', 'ES', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (68, 'Ethiopia', 'ET', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (69, 'Finland', 'FI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (70, 'Fiji', 'FJ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (71, 'Falkland Islands (Malvinas)', 'FK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (72, 'Micronesia, Federated States of', 'FM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (73, 'Faroe Islands', 'FO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (74, 'France', 'FR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (75, 'Gabon', 'GA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (76, 'United Kingdom', 'GB', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (77, 'Grenada', 'GD', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (78, 'Georgia', 'GE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (79, 'French Guiana', 'GF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (80, 'Guernsey', 'GG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (81, 'Ghana', 'GH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (82, 'Gibraltar', 'GI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (83, 'Greenland', 'GL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (84, 'Gambia', 'GM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (85, 'Guinea', 'GN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (86, 'Guadeloupe', 'GP', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (87, 'Equatorial Guinea', 'GQ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (88, 'Greece', 'GR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (89, 'South Georgia and the South Sandwich Islands', 'GS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (90, 'Guatemala', 'GT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (91, 'Guam', 'GU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (92, 'Guinea-Bissau', 'GW', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (93, 'Guyana', 'GY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (94, 'Hong Kong', 'HK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (95, 'Heard Island and McDonald Islands', 'HM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (96, 'Honduras', 'HN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (97, 'Croatia', 'HR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (98, 'Haiti', 'HT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (99, 'Hungary', 'HU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (100, 'Indonesia', 'ID', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (101, 'Ireland', 'IE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (102, 'Israel', 'IL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (103, 'Isle of Man', 'IM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (104, 'India', 'IN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (105, 'British Indian Ocean Territory', 'IO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (106, 'Iraq', 'IQ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (107, 'Iran, Islamic Republic of', 'IR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (108, 'Iceland', 'IS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (109, 'Italy', 'IT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (110, 'Jersey', 'JE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (111, 'Jamaica', 'JM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (112, 'Jordan', 'JO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (113, 'Japan', 'JP', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (114, 'Kenya', 'KE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (115, 'Kyrgyzstan', 'KG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (116, 'Cambodia', 'KH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (117, 'Kiribati', 'KI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (118, 'Comoros', 'KM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (119, 'Saint Kitts and Nevis', 'KN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (120, 'Korea, Democratic People''s Republic of', 'KP', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (121, 'Korea, Republic of', 'KR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (122, 'Kuwait', 'KW', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (123, 'Cayman Islands', 'KY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (124, 'Kazakhstan', 'KZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (125, 'Lao People''s Democratic Republic', 'LA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (126, 'Lebanon', 'LB', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (127, 'Saint Lucia', 'LC', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (128, 'Liechtenstein', 'LI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (129, 'Sri Lanka', 'LK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (130, 'Liberia', 'LR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (131, 'Lesotho', 'LS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (132, 'Lithuania', 'LT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (133, 'Luxembourg', 'LU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (134, 'Latvia', 'LV', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (135, 'Libyan Arab Jamahiriya', 'LY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (136, 'Morocco', 'MA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (137, 'Monaco', 'MC', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (138, 'Moldova, Republic of', 'MD', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (139, 'Montenegro', 'ME', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (140, 'Saint Martin (French part)', 'MF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (141, 'Madagascar', 'MG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (142, 'Marshall Islands', 'MH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (143, 'Macedonia, the former Yugoslav Republic of', 'MK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (144, 'Mali', 'ML', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (145, 'Myanmar', 'MM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (146, 'Mongolia', 'MN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (147, 'Macao', 'MO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (148, 'Northern Mariana Islands', 'MP', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (149, 'Martinique', 'MQ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (150, 'Mauritania', 'MR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (151, 'Montserrat', 'MS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (152, 'Malta', 'MT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (153, 'Mauritius', 'MU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (154, 'Maldives', 'MV', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (155, 'Malawi', 'MW', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (156, 'Mexico', 'MX', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (157, 'Malaysia', 'MY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (158, 'Mozambique', 'MZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (159, 'Namibia', 'NA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (160, 'New Caledonia', 'NC', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (161, 'Niger', 'NE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (162, 'Norfolk Island', 'NF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (163, 'Nigeria', 'NG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (164, 'Nicaragua', 'NI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (165, 'Netherlands', 'NL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (166, 'Norway', 'NO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (167, 'Nepal', 'NP', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (168, 'Nauru', 'NR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (169, 'Niue', 'NU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (170, 'New Zealand', 'NZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (171, 'Oman', 'OM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (172, 'Panama', 'PA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (173, 'Peru', 'PE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (174, 'French Polynesia', 'PF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (175, 'Papua New Guinea', 'PG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (176, 'Philippines', 'PH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (177, 'Pakistan', 'PK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (178, 'Poland', 'PL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (179, 'Saint Pierre and Miquelon', 'PM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (180, 'Pitcairn', 'PN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (181, 'Puerto Rico', 'PR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (182, 'Palestinian Territory, Occupied', 'PS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (183, 'Portugal', 'PT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (184, 'Palau', 'PW', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (185, 'Paraguay', 'PY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (186, 'Qatar', 'QA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (187, 'Reunion Réunion', 'RE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (188, 'Romania', 'RO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (189, 'Serbia', 'RS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (190, 'Russian Federation', 'RU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (191, 'Rwanda', 'RW', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (192, 'Saudi Arabia', 'SA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (193, 'Solomon Islands', 'SB', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (194, 'Seychelles', 'SC', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (195, 'Sudan', 'SD', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (196, 'Sweden', 'SE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (197, 'Singapore', 'SG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (198, 'Saint Helena', 'SH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (199, 'Slovenia', 'SI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (200, 'Svalbard and Jan Mayen', 'SJ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (201, 'Slovakia', 'SK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (202, 'Sierra Leone', 'SL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (203, 'San Marino', 'SM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (204, 'Senegal', 'SN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (205, 'Somalia', 'SO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (206, 'Suriname', 'SR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (207, 'São Tomé and Príncipe', 'ST', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (208, 'El Salvador', 'SV', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (209, 'Syrian Arab Republic', 'SY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (210, 'Swaziland', 'SZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (211, 'Turks and Caicos Islands', 'TC', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (212, 'Chad', 'TD', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (213, 'French Southern Territories', 'TF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (214, 'Togo', 'TG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (215, 'Thailand', 'TH', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (216, 'Tajikistan', 'TJ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (217, 'Tokelau', 'TK', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (218, 'Timor-Leste', 'TL', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (219, 'Turkmenistan', 'TM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (220, 'Tunisia', 'TN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (221, 'Tonga', 'TO', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (222, 'Turkey', 'TR', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (223, 'Trinidad and Tobago', 'TT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (224, 'Tuvalu', 'TV', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (225, 'Taiwan, Province of China', 'TW', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (226, 'Tanzania, United Republic of', 'TZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (227, 'Ukraine', 'UA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (228, 'Uganda', 'UG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (229, 'United States Minor Outlying Islands', 'UM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (230, 'United States', 'US', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (231, 'Uruguay', 'UY', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (232, 'Uzbekistan', 'UZ', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (233, 'Holy See (Vatican City State)', 'VA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (234, 'Saint Vincent and the Grenadines', 'VC', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (235, 'Venezuela, Bolivarian Republic of', 'VE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (236, 'Virgin Islands, British', 'VG', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (237, 'Virgin Islands, U.S.', 'VI', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (238, 'Viet Nam', 'VN', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (239, 'Vanuatu', 'VU', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (240, 'Wallis and Futuna', 'WF', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (241, 'Samoa', 'WS', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (242, 'Yemen', 'YE', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (243, 'Mayotte', 'YT', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (244, 'South Africa', 'ZA', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (245, 'Zambia', 'ZM', 1, 0, 0);
REPLACE INTO `zupal_place_countries` (`id`, `name`, `code`, `has_states`, `lat`, `long`) VALUES (246, 'Zimbabwe', 'ZW', 1, 0, 0);
