<?php
/* 
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

$this->dojo()->enable()
->addOnLoad('init_fisheye');

$this->headScript()->captureStart();
?>
var menu_items;
var originalHeight = new Object();
function init_fisheye()
{
	menu_items = dojo.query('.item');
dojo.forEach(menu_items,
	function (oneEntry, index)
	{
		originalHeight[oneEntry.id] = oneEntry.height
	}
);
}
      	
<? $this->headScript()->captureEnd(); ?>
<style>
#menu {
	float: right;
	width: 300px
}
.item
{
	border: 1px solid black;
	padding: 3px;
}
</style>
<div id="menu">
	<div class="item" id="menu_1">
	Item One
	</div>
	<div class="item" id="menu_2">
	Item Two
	</div>
	<div class="item" id="menu_3">
	Item Three
	</div>
	<div class="item" id="menu_4">
	Item Four
	</div>
	<div class="item" id="menu_5">
	Item Five
	</div>
</div>
