<?php
$this->placeholder('page_title')->set('Log Search Results');
?>

<?= $this->form->render() ?>

<h2>Hits</h2>

<div style="width: 800px; overflow: scroll; background-color: #f0f0f0;">
<pre>
<?= join("\n", $this->hits) ?>
</pre>
</div>

<h2>Sampled Lines</h2>

<div style="width: 800px; overflow: scroll; background-color: #f0f0f0;">
<pre>
<?
if (@Zupal_Bootstrap::$registry->log_set ):
	foreach(Zupal_Bootstrap::$registry->log_set as $k => $v) echo "$k: $v\n";
endif;
?>
</pre>
</div>