<fieldset class="ult_groupinfo">
    <legend>Group <?= $this->group->get_title() ?></legend>
     <?= $this->powerMatrix($this->group) ?>
    <p><b><?= $this->group->get_lead() ?></b>:
        <?= $this->group->get_content(); ?></p>

<span class="button_link_list">
    <ul>
        <li><a href="<?= $this->baseUrl() ?>/admin/ultimatum/groups">List Groups</a></li>       
        <li><a href="<?= $this->baseUrl() ?>/admin/ultimatum/groupedit/id/<?= $this->group->identity() ?>" >Edit</a></li>
        <li><a href="<?= $this->baseUrl() ?>/admin/ultimatum/groupnew">Add New Group</a></li>
    </ul>
</span>
</fieldset>
<?
$this->headStyle()->captureStart();
echo '@import "/style/ultimatum/ult_style.css";';
$this->headStyle()->captureEnd();
$this->placeholder('page_title')->set('Group ' . $this->group);