<?
$this->placeholder('page_title')->set('Ultimate Groups');

        $filename = dirname(__FILE__) . '/group_grid.ini';
        $col = new Zend_Config_Ini($filename, 'columns');
        $this->columns = $col->toArray();

$this->headScript()->captureStart();
?>
function groups_grid_edit_formatter(p)
{
    return '<a href="<?= $this->baseUrl() ?>/admin/ultimatum/groupdit/resource_id/'
        + p + '"><img src="<?= $this->baseUrl() ?>/images/icons/edit.gif" height="20" width="20" border="0"/></a>';
}

<?  $this->headScript()->captureEnd();   ?>

<?= $this->dojostore('groups_store', $this->baseUrl() . '/admin/ultimatum/groupsstore') ?>
<?= $this->dojogrid('groups', 'groups_store', $this->columns, 'id') ?>

<a href="<?= $this->baseUrl() ?>/admin/ultimatum/groupnew" class="linkbutton">Add group</a>