<?
    $this->placeholder('title')->set('Add Domain');
    $break = 0;
?>
<h2>Create Domain for Table... in module <?= $this->domain_module ?> </h2>
<table class="layout_table button_table">
<tr>
<? 
$page_data = array(
    'module' => 'administer',
    'controller' => 'meta',
    'class' => 'linkbutton',
    'action' => 'adddomaincreate',
    'params' => array('module_domain' => $this->domain_module)
);

foreach($this->tables as $table):
$page_data['label'] = $table;
$page_data['params']['table'] = $table;
$page = Zend_Navigation_Page::factory($page_data);
?>
    <td><?= $this->navigation()->htmlify($page) ?> </td>
<?
    ++$break;
    if ($break == 3){ echo '</tr><tr>';
    $break = 0; }
?>
<? endforeach; ?>
</tr>
</table>