<?
    $this->placeholder('page title')->set('Add Form');
    $break = 0;
    $link_params = array(
    'module' => 'administer',
    'controller' => 'meta',
    'label' => '',
    'action' => 'addformcreate',
    'class' => 'linkbutton',
    'params' => array('module_domain' => $this->domain_module)
);
?>
<h2>Create Form for Table... in module <?= $this->domain_module ?> </h2>
<table class="layout_table button_table">
<tr>
<? foreach($this->tables as $table):
$link_params['label'] = $table;
$link_params['params']['table'] = $table;
?>
        <td><?= $this->navigation()->htmlify(Zend_Navigation_Page::factory($link_params)) ?></td>
    
<?
    ++$break;
    if ($break == 3){ echo '</tr><tr>';
    $break = 0; }
?>
<? endforeach; ?>
</tr>
</table>