<?
    $this->placeholder('page title')->set('Add Form');
    $break = 0;
?>
<h2>Create Form for Table... in module <?= $this->domain_module ?> </h2>
<table class="layout_table button_table">
<tr>
<? foreach($this->tables as $table): ?>
        <td><a href="<?= new Zend_Navigation_Page_Mvc(array(
    'module' => 'administer',
    'controller' => 'meta',
    'action' => 'addformcreate',
    'params' => array('module_domain' => $this->domain_module),
        'table' => $table
)) ?>"><?= $table ?></a>
    </td>
    
<?
    ++$break;
    if ($break == 3){ echo '</tr><tr>';
    $break = 0; }
?>
<? endforeach; ?>
</tr>
</table>