<?php

	$this->placeholder('page_title')->set('People');
	/*
	$breadcrumb = $this->placeholder('breadcrumb');
	$breadcrumb = $breadcrumb[0];
	$breadcrumb->set_item('People');
	$this->placeholder('breadcrumb')->set($breadcrumb);
*/
			 
?>
<?= Zupal_People::getInstance()->render_grid($this,'list',
	 array(
			'person_id' => array('label' => 'ID', 'width' => 40),
			'gender' => array('label' => 'G', 'width' => 20),
			'name_first' => array('label' => 'First Name', 'width' => 80),
			'name_last' =>  array('label' => 'Last Name', 'width' => 100),
			'username' => array('label' => 'User', 'width' => 80),
			'email' => array('label' => 'eMail', 'width' => 200)
		),
		Zend_Controller_Front::getInstance()->getBaseUrl() . '/people/item/data' ) ?>

<table width="100%">
<tr>

	<td width="1*"  valign="top">
	<h2>Add People</h2>

<?= $this->form->render() ?>
	</td>
	<td width="1*" valign="top">
	<h2>Find People</h2>

<?= $this->people_form->render() ?>
	</td>
</tr>
</table>
