<?
$this->placeholder('page_title')->set('Game: Game Types');
$grid_options = array();

$filename = dirname(__FILE__) . '/gametypesitems_grid.ini';
$col = new Zend_Config_Ini($filename, 'columns');

$this->headScript()->captureStart();
?>

function gametype_grid_view_formatter(p)
{
    return '<a href="<?= $this->baseUrl() ?>/admin/games/gametypesview/id/'
        + p + '"><img src="<?= $this->baseUrl() ?>/images/icons/view.gif" height="20" width="20" border="0"/></a>';
}

function gametype_grid_edit_formatter(p)
{
    return '<a href="<?= $this->baseUrl() ?>/admin/games/gametypesedit/id/'
        + p + '"><img src="<?= $this->baseUrl() ?>/images/icons/edit.gif" height="20" width="20" border="0"/></a>';
}

<?  $this->headScript()->captureEnd();   ?>

<?= $this->dojostore('gametypes_store', $this->baseUrl() . '/game/admin/gametypesstore') ?>
<?= $this->dojogrid('gametypes_grid', 'gametypes_store', $col, 'id', NULL, $grid_options) ?>

<?= $this->zupallinkbutton('/admin/game/gametypesnewitem', 'Add Game Type') ?>