<?php
	$this->placeholder('page_title')->set($this->artist->name);
	$this->dojo()
	->requireModule('dijit.form.Button')
	->requireModule('dijit.layout.ContentPane')
	->requireModule('dojo.parser')
	->enable();
	$this->headScript()->captureStart();
?>
dojo.provide('zupal.media.musicbrainz.Artist');
zupal.media.musicbrainz.Artist =
{
	loadArtist: function(artist_json)
	{
		alert('got it');
		var artist_info_name = dijit.byId('artist_info_name');
		artist_info_name.attr('content', artist_json.artist.name);

		dojo.query('.person_row').forEach(dojo.destroy);

		var artist_info_artist = dojo.byId('artist_info_artist');
		for(i = 0; i < artist_json.people.length; ++i)
		{
			dojo.place(this.peopleRow(artist_json.people[i]), artist_info_artist, 'last');
		}

		dojo.query('.group_row').forEach(dojo.destroy);

		var artist_info_groups = dojo.byId('artist_info_groups');
		for(i = 0; i < artist_json.groups.length; ++i)
		{
			dojo.place(this.groupRow(artist_json.groups[i]), artist_info_groups, 'last');
		}
	}
	,
	peopleRow: function(person)
	{
		/*var new_row = document.createElement('tr');
		var type_cell = document.createElement('td');
		type_cell.innerHTML =  person.type_name;
		dojo.place(type_cell, new_row, 'last');

		var person_cell = document.createElement('td');
		person_cell.innerHTML =  this.peopleLink(person);
		dojo.place(person_cell, new_row, 'last');
		return new_row;*/

		return this.tableRow(person.type_name, this.peopleLink(person), 'people_row');
	},

	tableRow: function(cell1, cell2, rowClass)
	{
		var new_row = document.createElement('tr');
		dojo.addClass(new_row, rowClass);
		
		var type_cell = document.createElement('td');
		dojo.place(type_cell, new_row, 'last');
		type_cell.innerHTML =  cell1;

		var person_cell = document.createElement('td');
		dojo.place(person_cell, new_row, 'last');
		person_cell.innerHTML =  cell2;

		return new_row;
	},

	peopleLink: function(person)
	{
		return '<a href="javascript: void()" onClick="zupal.media.musicbrainz.Artist.fetchArtist(\'' + person.gid + '\')">' + person.name + '</a>';
	},

	groupRow: function(group)
	{
		var person_text = '';
		for(i = 0; i < group.people.length; ++i)
		{
			person = group.people[i];
			person_text += this.peopleLink(person) + '<br />';
		}
		return tableRow(group.name, person_text, 'group_row');
	},

	fetchArtist: function(gid)
	{
		dojo.xhrPost(
			{
				url: '<?= ZUPAL_BASEURL ?>/mb/artist/'  + gid,
				load: dojo.hitch(zupal.media.musicbrainz.Artist, function(response){this.loadArtist(response);}),
				handleAs: 'json'
			}
		);
	}
}

dojo.addOnLoad(
	function ()
	{
		zupal.media.musicbrainz.Artist.fetchArtist('<?= $this->artist->gid ?>');
	}
);
<?
	$this->headScript()->captureEnd();
?>

<table>
	<thead>
	<tr>
		<td colspan="2">
			<dl>
				<dt>Artist</dt>
				<dd id="artist_info_name" dojoType="dijit.layout.ContentPane">&nbsp;</dd>
			</dl>
		</td>
	</tr>

	<tr>
		<th>Relationship</th>
		<th>Artist</th>
	</tr>
	</thead>

	<tbody id="artist_info_artist">
	</tbody>

	<tbody>
		<tr>
			<th>Group</th>
			<th>Members</th>
		</tr>
	</tbody>

	<tbody id="artist_info_groups">
	</tbody>
</table>

<br clerar="all" />

<h2>Data</h2>

<dl>
	<dt>Name</dt>
	<dd><?= $this->artist->name ?></dd>
	<dt>Type</dt>
	<dd><?= $this->artist->type() ?></dd>
<? if ($this->artist->is_person()): ?>
	<dt>Group(s)</dt>
	<dd>
	<ol>
		<? foreach($this->artist->groups() as $group): ?>
		<li><?= $group->artist->name ?> (<?= $group->type->name ?>)
		<ul>
<? foreach ($group->artist->people() as $person): ?>
			<li>
				<?= $person->artist->name ?>(<?= $person->type->name ?>)
			</li>
<? endforeach; ?>
		</ul>
		</li>
		<? endforeach; ?>
	</ol>
	</dd>
<? endif; ?>
	<dt>People</dt>
	<dd>
		<ol>
<? foreach($this->artist->people() as $person): ?>
			<li>
				<?= $person->artist->name ?>(<?= $person->type->name ?>)
			</li>
<? endforeach; ?>
		</ol>
	</dd>
</dl>

<h2>JSON</h2>

<textarea rows="30" cols="40">
<?= stripslashes($this->artist->json()) ?>
</textarea>

<pre>
<? print_r($this->artist->json_data()) ?>
</pre>
