<?
$this->placeholder("page_title")->set("Table Definiitions");

$this->dojo()->requireModule('dijit.form.Form')
	->addStylesheet('http://ajax.googleapis.com/ajax/libs/dojo/1.2.0/dojo/resources/dojo.css')
	->requireModule('dijit.form.Button')
	->requireModule('dijit.layout.ContentPane')
	->requireModule('dojo.parser')
	->setCdnBase(Zend_Dojo::CDN_BASE_GOOGLE)
	->useCdn();
	
$this->tabContainer()->captureStart('db', array( 'style'=>"width: 800px; height: 400px"));
?>
<div id="main_db" dojoType="dijit.layout.ContentPane" title="Main Database" selected="true">
<table>
<tr>
	<th>Tables</th>
	<th>Code </th>
</tr>

<tr>
	<td valign="top">
<dl>
<? foreach($this->tables as $table): ?>
	<dt>
<?=  new Zupal_Control_Link($table, array('target' => 'table_def',
		'module' => 'admin',
		'controller' => 'modules',
		'action' => 'tableclass',
		'style' => 'font-size: 80%; font-weight: normal',
		'table' => $table)) ?>
	</dt>
<? endforeach; ?>
</dl>
</td>
<td valign=top>
	<iframe name="table_def" width="600" height="800">
	<p>Click a link at the left</p>
	</iframe>
</td>
</table>
</div>
<? foreach (Zupal_Module_Manager::getInstance()->databases() as $db_name => $adapter): ?>
<div id="db2" dojoType="dijit.layout.ContentPane" title="<?= ucwords($db_name) ?>">
	<table>
	<tr>
	<th>Tables</th>
	<th>Code </th>
</tr>
<tr>
	<td valign="top">
	<?= $this->partial('modules/tableLinks.phtml', array('db_name' => $db_name,
		'adapter' => $adapter)) ?>
	</td>

	<td valign="top">
		<iframe name="table_def_<?= $db_name ?>" width="600" height="800">
	<p>Click a link at the left</p>
	</iframe>
	</td>
</tr>
	</table>
</div>
<? endforeach; ?>

<?= $this->tabContainer()->captureEnd('db'); ?>