<?
	$this->placeholder('page_title')->set('Music Brainz');
?>

<fieldset>
	<?= new Zupal_Control_IconLink(
	'http://wiki.musicbrainz.org/-/skins/musicbrainzcommon/musicbrainz_logo.png',
	'Import MusicBrainz data',
		array(
			'module' => 'media',
			'controller' => 'musicbrainz',
			'action' => 'load'
		)
	) ?>
	<?= new Zupal_Control_IconLink(
	'http://wiki.musicbrainz.org/-/skins/musicbrainzcommon/musicbrainz_logo.png',
	'Artists',
		array(
			'module' => 'media',
			'controller' => 'musicbrainz',
			'action' => 'artists'
		)
	) ?>

	<?= new Zupal_Control_IconLink(
	'http://wiki.musicbrainz.org/-/skins/musicbrainzcommon/musicbrainz_logo.png',
	'Data',
		array(
			'module' => 'media',
			'controller' => 'musicbrainz',
			'action' => 'findartist'
		)
	) ?>

</fieldset>