<?
$this->placeholder('page_title')->set('Modules');
?>

<table>
    <tr>
        <?
        $mm = $this->modules[0];
        foreach (array_keys($mm->toArray()) as $t): ?>
        <th><?= $t ?></th>
        <? endforeach; ?>

    </tr>

<? foreach ($this->modules as $m): ?>
    <tr>
        <td>
            <?= join($m->toArray(), '</td><td>') ?>
        </td>

    </tr>
        <? endforeach; ?>

</table>