<?
$this->placeholder('page_title')->set('Edit Menu');
$this->dojo()->requireModule('dojo.data.ItemFileReadStore')
->requireModule('dijit.tree.ForestStoreModel')
->requireModule('dijit.Tree')
->requireModule('dijit.form.Button')
->requireModule('dijit.layout.BorderContainer')
->requireModule('dijit.layout.ContentPane')
->requireModule('dojo.parser')
->setDjConfigOption('parseOnLoad', TRUE);

$form = new Administer_Form_Zupalmenus();
$form->setAttrib('id', 'menu_form');
$form->setName('menu_form');

$this->headScript()->appendFile('/scripts/multiple-select-functions.js');
?>
<script language="javascript">
<? 
$this->headScript()->captureStart();
?>
    var last_menu_selected = false;

    function update_menu_form(item)
    {
        var f = document.forms['menu_form'];

        f.elements['id'].value = item.id;
        f.elements['label'].value = item.label;
        f.elements['name'].value = item.name;
        f.elements['parent'].value = item.parent;
        f.elements['module'].value = item.module;
        f.elements['controller'].value = item.controller;
        f.elements['action'].value = item.action;
        f.elements['href'].value = item.href;
        f.elements['parameters'].value = item.parameters;
        f.elements['callback_class'].value = item.callback_class;
        dojo.query('#if_module').forEach(
        function(i){i.checked = item.if_module[0] ? true : false; }
        ); //
        dojo.query('#if_controller').forEach(
        function(i){i.checked = item.if_controller[0] ? true : false; }
        ); //
        var found = 0;
        var res_select = f.elements['resource'];
        
        if (item.resource != "")
        {
            found = FM.findOption(res_select, item.resource);
         //   alert(item.resource + " found at " + found);
        }
        res_select.selectedIndex = found;
        found = 0;
        var mod_select = f.elements['module'];
        if (item.module != "")
        {
            found = FM.findOption(mod_select, item.module);
          //  alert("found " + item.module + " at " + found);
        }
        mod_select.selectedIndex = found;
    }
<? $this->headScript()->captureEnd(); ?>
</script>
<style>
    <? $this->headStyle()->captureStart(); ?>
#parent-label,
#parent-element,
#id-label,
#id-element,
#created_by_module-label,
#created_by_module-element,
#sort_by-label,
#sort_by-element
{
    display: none;
}

#main #form_panel .zend_form input[type="button"],
#main #form_panel .zend_form input[type="submit"]
{
    border-bottom: 2px solid black;
    background-color: #666;
    color: white;
    font-weight: bold;/*
    margin-left: 120px; */
}

#main #form_panel label
{
    font-weight: normal;
    font-size: 80%;
}

#main #form_panel dl.zend_form input,
#main #form_panel dl.zend_form textarea,
#main #form_panel dl.zend_form select
{
    font-size: 80%;
    border: 1px solid #999;
    background-color: white;
    width: 250px;
}
<? $this->headStyle()->captureEnd(); ?>
</style>

<div dojoType="dojo.data.ItemFileReadStore"
     url="<?=$this->baseUrl() ?>/administer/modules/menustore"
     jsId="menu_tree_data"
     >
</div>

<div dojoType="dijit.tree.ForestStoreModel"
     rootLabel="Menus"
     rootId="0"
     store="menu_tree_data"
     childrenAttrs="children"
     jsId="menu_tree_model"
     >
</div>
<div dojoType="dijit.layout.BorderContainer" style="width: 800px; height: 600px" gutters="false" id="menu_edit_frame">
    <div dojoType="dijit.layout.ContentPane" region="center" style="width: 40%">
<div dojoType="dijit.Tree" id="menu_tree"
     model="menu_tree_model">
    <script type="dojo/method" event="onClick" args="item">
        last_menu_selected = item;
        if (item.id)
            {
                update_menu_form(item);
            }
    </script>
</div>
    </div>
    <div dojoType="dijit.layout.ContentPane" region="right" style="width: 60%"   id="form_panel">

            <div dojoType="dijit.form.Button">
                Edit Selected Menu
                <script type="dojo/method" event="onClick" args="evt">
                    if (last_menu_selected)
                        {
                            f =
                            alert("selected " + last_menu_selected.id);
                        }
                </script>
            </div>

            <?= $form ?>
    </div>

</div>