<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<?
if ($this->dojo()->isEnabled())
{
   $this->dojo()
	//->setCdnBase(Zend_Dojo::CDN_BASE_GOOGLE)
	->setLocalPath(ZUPAL_BASEURL . '/scripts/Dojo/dojo/dojo.js')
	->requireModule('dijit.form.Form')
    ->addStyleSheetModule('dijit.themes.tundra')
	->useCdn();
   

}
?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<? if ($this->dojo()->isEnabled()) echo $this->dojo(); ?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()->appendStylesheet(ZUPAL_BASEURL . '/css/styles.css');  ?>
    <?php echo $this->headScript()?>
    <?php echo $this->headStyle() ?>

</head>
<body class="tundra">
	<div id="container">
		<div id="header">
			<h1>Zupal</h1>
			<? if ($this->placeholder('breadcrumb')): ?>
			<div id="breadcrumb"><?= $this->placeholder('breadcrumb') ?></div>
			<? endif; ?>
		</div>
	  
	    <div id="nav">
		<?php echo $this->placeholder('nav') ?>
		<?=  $this->loginPanel() ?></div>

	    <div id="content">		
<? if ($this->placeholder('message')): ?>
		<div id="message"><?= $this->placeholder('message') ?></div>
<? endif; ?>

<? if ($this->placeholder('error')): ?>
		<div id="error"><?= $this->placeholder('error') ?></div>
<? endif; ?>
		<? if ($this->placeholder('page_title')): ?>
		<h1><?= $this->placeholder('page_title') ?></h1>
		<? endif; ?>
	    	<?php echo $this->layout()->content ?>
	    </div>
	    
    </div>
</body>
</html>