<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()->appendStylesheet(ZUPAL_BASEURL . '/css/styles.css');  ?>
    <?php echo $this->headScript()?>
    <?php echo $this->headStyle() ?>
<?

if ($this->dojo()->isEnabled()){
    $this->dojo() //->setLocalPath($this->placeholder('base_path') . '/scripts/Dojo/dojo/dojo.js') note - changed to Google
                 ->addStyleSheetModule('dijit.themes.tundra');
    echo $this->dojo();
   }
?>
</head>
<body>
	<div id="container">
		<div id="header">
			<h1>Zupal</h1>
			<? if ($this->placeholder('breadcrumb')): ?>
			<div id="breadcrumb"><?= $this->placeholder('breadcrumb') ?></div>
			<? endif; ?>
		</div>
	  
	    <div id="nav"><?php echo $this->placeholder('nav') ?></div>


	    <div id="content">		
<? if ($this->placeholder('message')): ?>
		<div id="message"><?= $this->placeholder('message') ?></div>
<? endif; ?>

<? if ($this->placeholder('error')): ?>
		<div id="error"><?= $this->placeholder('error') ?></div>
<? endif; ?>
		<? if ($this->placeholder('page_title')): ?>
		<h1><?= $this->placeholder('page_title') ?></h1>
		<? endif; ?>
	    	<?php echo $this->layout()->content ?>
	    </div>
	    
    </div>
</body>
</html>