<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()->appendStylesheet('/css/styles.css');  ?>
    <?php echo $this->headScript()?>
    <?php echo $this->headStyle() ?>
</head>
<body>
	<div id="container">
		<div id="header">
			<h1>Zupal</h1>
		</div>
	  
	    <div id="nav"><?php //echo $this->placeholder('nav') ?></div>
	
	    <div id="content">
	    	<?php echo $this->layout()->content ?>
	    </div>
	    
    </div>
</body>
</html>