<!DOCTYPE html
    PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()->appendStylesheet(ZUPAL_BASEURL . '/css/popup.css');  ?>
    <?php echo $this->headScript()?>
    <?php echo $this->headStyle() ?>
<?

if ($this->dojo()->isEnabled()){
    $this->dojo() //->setLocalPath($this->placeholder('base_path') . '/scripts/Dojo/dojo/dojo.js') note - changed to Google
                 ->addStyleSheetModule('dijit.themes.tundra');
    echo $this->dojo();
   }
?>
</head>
<body>
<?php echo $this->layout()->content ?>
</body>
</html>