<?

$this->placeholder('page_title')->set('Employees');

$pColumns = array(
	'eid' => array('label' => 'ID', 'width' => 40),
	'employee_gender' => array('label' => 'G', 'width' => 20),
	'employee_name_first' => array('label' => 'First Name', 'width' => 80),
	'employee_name_last' =>  array('label' => 'Last Name', 'width' => 100),
	'salary' => array('label' => 'Salary', 'width' => 80),
	'status' => array('label' => 'Status', 'width' => 120),
	'employee_email' => array('label' => 'eMail', 'width' => 200)
);
$pURL = ZUPAL_BASEURL . DS . join(DS, array('people', 'employees', 'data'));
echo Zupal_Employees::getInstance()->render_grid($this, 'list', $pColumns, $pURL);
?>
<h2>Create Employee</h2>

<?= $this->new_form->render() ?>